author: mahoutsukaii
database: false
description: handles and reports bans with coordinates and additional notes.
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: jadon.mahoutsukaii.plugins.banreport.BanReport
name: BanReport
startup: postworld
url: http://jadon-mc.net/
version: '1.1'

commands:
  ban:
    description: Ban a player.
    usage: /<command> [player] {-s} [reason]
  tempban:
    description: temporarily ban a player.
    usage: /<command> [player] {-s} [time][s/m/h/d] [reason]
  banip:
    description: bans an IP address.
    usage: /<command> [IP]
  unban:
    description: unban a player.
    usage: /<command> [player] {-s}
  kick:
    description: kick a player from the server.
    usage: /<command> [player] {-s} [reason]
  baninfo:
    description: View notes on a banned player.
    usage: /baninfo [player]
  addinfo:
    description: Add additional information regarding a banned player.
    usage: /addinfo [player] [info]
  removeinfo:
    description: Removes information regarding a banned player.
    usage: /removeinfo [player] [id]
  bantp:
    description: teleports the player to the point where data was added.
    usage: /<command> [player] [id]
  banexport:
    description: exports the SQL ban list to a file.
    usage: /<command>
  banimport:
    description: imports the banned-players.txt to the database
    usage: /<command>